#!/bin/sh
cd $(dirname $0)
r="$PWD"

doc="$r"/DOC
rm -fr "$doc"
mkdir "$doc" || exit

lambda="$r"/化/述.scrbl
scribble --dest "$doc" --html --dest-name lambda.html $lambda &
scribble --dest "$doc" --markdown --dest-name lambda.md $lambda &
md_lambda="$doc"/lambda.md
html_lambda="$doc"/lambda.html

wait

cat > "$r"/README.md <<EOF
語
==
Copyright (C) 2014-2018  Zaoqi <zaomir@outlook.com>

化
--
[HTML](DOC/lambda.html)
$(cat "$md_lambda")
EOF
